on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_app:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Assemble APK
        run: ./gradlew assembleDebug